<?php

/**
 * @file
 * Contains newscoop.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function newscoop_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the newscoop module.
    case 'help.page.newscoop':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Newscoop Related Functionalities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 *
 * Modifying news and articles and filter them out for reports and public.
 */
function newscoop_cron() {
	
}